version: '3.8'

services:
  smart-retail-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_retail_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
